### ISSUE TITLE
Problème dans le code de l'identification

### ISSUE THREAD

**Issue by Alastrael** [Orogarde/Projet_Web_M2L#1]
Bonjour, 
Dans votre code, vous devriez changer le type de l'input du mot de passe qui est en "text" en "password", cela évitera que l'utilisateur puisse voir la saisie.
input type="password" id="nm" name="motdepasse" size="25" placeholder="mdp..." maxlength="50" required 
à la place de : 
input type="text" id="nm" name="motdepasse" size="25" placeholder="mdp..." maxlength="50" required

**Comment by Alastrael** [comment]
*<input type="password" id="nm" name="motdepasse" size="25" placeholder="mdp..." maxlength="50" required />*

*<input type="text" id="nm" name="motdepasse" size="25" placeholder="mdp..." maxlength="50" required />*

**Comment by Orogarde** [comment]
Bonjour , Merci de votre aide je vais modifier cela de suite !
Cordialement.

**Comment by Orogarde** [comment]
je viens de modifier le code , merci encore !
